import Head from 'next/head'
import Navigation from "../components/navigation";
export default function Home() {
  return (
    <>
      <Head>
        <title>Eden Digtial</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className='absolute font-extrabold' style={{top: '45%'}}>
            <h1 className='text-4xl text-white'>Разработка сайтов для бизнеса</h1>
            <div className='pt-5 text-sm'>
                <p>
                    Мы специализируемся на разработке адаптивных веб-сайтов,
                </p>
                <p>сайтов электронной коммерции и веб-приложений для компаний и организаций,</p>
                <p>которым нужен веб-сайт мирового класса.</p>
            </div>
        </div>
    </>
  )
}
